spring:
  application:
    name: transacoes-service
  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
