spring:
  application:
    name: processamento-service
  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        prefetch: 10
    template:
      mandatory: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

credpay:
  outbox:
    publisher:
      enabled: ${CREDPAY_OUTBOX_PUBLISHER_ENABLED:false}
      interval: ${CREDPAY_OUTBOX_PUBLISHER_INTERVAL:PT1S}

management:
  health:
    rabbit:
      enabled: ${credpay.outbox.publisher.enabled:false}
  endpoints:
    web:
      exposure:
        include: health
