spring:
  application:
    name: processamento-service
  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

management:
  health:
    rabbit:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health
