apiVersion: v1
kind: ConfigMap
metadata:
  name: credpay-config
data:
  SPRING_RABBITMQ_HOST: rabbit
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_VIRTUAL_HOST: /
  BRL_LIMIT: "100.00"
  MANAGEMENT_HEALTH_RABBIT_ENABLED: "true"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_ENDPOINT_HEALTH_GROUP_READINESS_INCLUDE: readinessState,db,rabbit
